version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      
  test:
    docker: # it uses the docker executor
      - image: mthaallalaksh/ftnt:hello-mahesh
        auth:
          username: mthaallalaksh
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: "docker run mthaallalaksh/ftnt:hello-mahesh"

workflows:
  test:
    jobs:
      - build
      - test  
          