version: 2.1
jobs:
  build-test:
    machine: yes
    steps:
      - checkout
      - run: |
          docker login --username mthaallalaksh --password $DOCKERHUB_PASSWORD
          docker run mthaallalaksh/ftnt:hello-mahesh

workflows:
  test:
    jobs:
      - build-test