name: FortiDevSec Scanner CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run the Docker image for SAST
      run: docker run hello-world
    - name: Run the Docker image for DAST
      run: docker run hello-world
